-- schema.sql

-- 1. Create a table for Games
CREATE TABLE public.games (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users NOT NULL,
  game_id integer NOT NULL, -- RAWG Game ID
  name text NOT NULL,
  image text,
  category text NOT NULL DEFAULT 'backlog',
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create a table for User Preferences (optional, can also just use localStorage for theme, but good for profile pic)
CREATE TABLE public.profiles (
  id uuid REFERENCES auth.users PRIMARY KEY,
  theme text DEFAULT 'dark',
  profile_pic text
);

-- 3. Set up Row Level Security (RLS)
-- Enable RLS
ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Games Policies
CREATE POLICY "Users can insert their own games."
  ON public.games FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own games."
  ON public.games FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update their own games."
  ON public.games FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own games."
  ON public.games FOR DELETE USING (auth.uid() = user_id);

-- Profiles Policies
CREATE POLICY "Users can view their own profile."
  ON public.profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update their own profile."
  ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 4. Automatically create a profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, profile_pic)
  VALUES (new.id, 'https://ui-avatars.com/api/?name=' || new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
